import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registry";
import GlobalStyle from "./reset";

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create-next-app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <StyledComponentsRegistry>
            <GlobalStyle />
            {children}
          </StyledComponentsRegistry>
        </body>
    </html>
  );
}
